[build]

# Raspberry Pi 4 64-bit
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-none-linux-gnu-gcc"
strip = { path = "aarch64-none-linux-gnu-strip" }

# Raspberry Pi 3 32-bit
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
strip = { path = "arm-linux-gnueabihf-strip" }
